# Generated by Django 6.0.5 on 2026-06-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggify', '0004_alter_comment_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
